name: model-train-eval
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup CML
        uses: iterative/setup-cml@v1
      - name: Train and evaluate model, publish results
        run: |
          pip3 install tensorflow matplotlib pandas numpy
          python3 simple_regression.py 100
          python3 evaluate.py
          
          cat lego_reg_results.csv >> report.md
          cml-publish error_plot.jpg --md >> report.md
          cml-send-comment report.md
          cml-send-github-check report.md
        shell: bash
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
